---
version: '2'
services:
  chap6-app:
    build: app
    hostname: app
    env_file: environment.txt
    ports:
      - "80:3000"
    restart: always
    networks:
      - chap5

  chap6-db:
    image: mysql:5.7.11
    env_file: environment.txt
    volumes:
      - mysql:/var/lib/mysql
    # ports:
    #     - '127.0.0.1:5432:5432'
    networks:
        - chap5

volumes:
  mysql:
    driver: local

networks:
  chap5:
    driver: bridge
